[build]
  command = "npm run build && npm run export"
  functions = "api"
  publish = "out"


# access auth page regardless of whether you're authenticated
[[redirects]]
	from = "/"
	to = "/"
	status = 200

# if authenticated, access everything
[[redirects]]
	from = "/*"
	status = 200
	force = true
	conditions = {Role = ["premium"]}

# for everything else, you're pushed to the auth page with 401
[[redirects]]
	from = "/posts/premium/*"
	to = "/"
  status = 401
	force = true