[build]
  command = "npm run build && npm run export"
  functions = "api"
  publish = "out"

[[redirects]]
  from = "/oh"
  to = "/test"
  status = 200
  force = false
  conditions = {Role = ["premium"]}

[[redirects]]
  from = "/oh"
  to = "/fail"
  status = 200
  force = false
