[build]
  command = "npm run build && npm run export"
  functions = "api"
  publish = "out"

[[redirects]]
  from = "/test"
  to = "/test"
  status = 200
  force = false
  conditions = {Role = ["premium"]}

[[redirects]]
  from = "/test"
  to = "/404
  status = 404
  force = false